# Generated by Django 4.1.2 on 2022-11-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateTimeField()),
                ('fcm_token', models.CharField(default=None, max_length=512, null=True)),
            ],
            options={
                'unique_together': {('full_name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='SelfReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pss_control', models.IntegerField()),
                ('pss_confident', models.IntegerField()),
                ('pss_yourway', models.IntegerField()),
                ('pss_difficulties', models.IntegerField()),
                ('stresslvl', models.IntegerField()),
                ('social_settings', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('activity', models.CharField(max_length=128)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='BVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Accelerometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.participant')),
            ],
        ),
    ]
