# Generated by Django 4.1.2 on 2022-11-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_offbody_id_alter_selfreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
