# Generated by Django 4.1.2 on 2022-11-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_value_bvp_light_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('is_off_body', models.BooleanField()),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.participant')),
            ],
        ),
    ]
