# Generated by Django 4.1.2 on 2022-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_participant_smartwatch_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emadata',
            name='response',
        ),
        migrations.AddField(
            model_name='emadata',
            name='activity',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='emadata',
            name='location',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='emadata',
            name='pss_confident',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='emadata',
            name='pss_control',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='emadata',
            name='pss_difficulties',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='emadata',
            name='pss_yourway',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='emadata',
            name='social_settings',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='emadata',
            name='stresslvl',
            field=models.IntegerField(default=-1),
        ),
    ]
