# Generated by Django 4.1.3 on 2022-11-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_selfreportlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelfReportLog',
        ),
    ]
