# Generated by Django 4.1.2 on 2022-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_emadata_response_emadata_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emadata',
            name='activity',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='emadata',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='emadata',
            name='pss_confident',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emadata',
            name='pss_control',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emadata',
            name='pss_difficulties',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emadata',
            name='pss_yourway',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emadata',
            name='social_settings',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='emadata',
            name='stresslvl',
            field=models.IntegerField(),
        ),
    ]
