# Generated by Django 4.1.2 on 2022-11-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emadata_activity_alter_emadata_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccelerometerData',
            new_name='Accelerometer',
        ),
        migrations.RenameModel(
            old_name='BVPData',
            new_name='BVP',
        ),
        migrations.RenameModel(
            old_name='EMAData',
            new_name='SelfReport',
        ),
        migrations.DeleteModel(
            name='SensingDataCount',
        ),
    ]
