# Generated by Django 4.1.3 on 2022-11-29 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_screenstate_location_calllog_activitytransition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('start_ts', models.BigIntegerField()),
                ('end_ts', models.BigIntegerField()),
                ('event_location', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
