# Generated by Django 4.1.3 on 2022-11-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_location',
            field=models.CharField(max_length=256),
        ),
    ]
